---
title: "About Me"
sidebar: false 
---

# Education

-   B.S., Industrial Engineering, Hacettepe University, Turkey, 2021 - ongoing.

# Work Experience

## Employements

1.  Türksat, Candidate Engineer, 2025- ongoing

2.  Let's FutureUp, Graphic Designer, 2024

3.  Europe Coding School, Sales Representative, 2024

## Internships

1.  Yarış Kabin San. ve Tic. A.Ş. , Quality Control Intern, 2025

2.  TANAP, Human Resources Intern, 2024

3.   Cargill, Planning Intern, 2024

# Projects

1.  **Comparative Analysis of CPM and PERT Limitations in Stochastic Project Environments Using Monte Carlo Simulation:** This project analyzes the limitations of CPM and PERT scheduling methods in stochastic project environments. Using Monte Carlo Simulation, the study compares deterministic estimates with simulated outcomes to evaluate schedule risk and estimation accuracy.
2.  **Library Occupancy Monitoring System:** This project was developed as part of the Database Management Systems course. Using SQL, we designed a database system that analyzes real-time library occupancy data. The system helps monitor library usage and provides insights into how study spaces are utilized.
3.  **auraFY Desk: Smart Music Display & Controller:** This project focuses on developing a smart desktop device that enables users to control Spotify music without relying on a phone or main screen. The product combines a circular touch display and physical interaction to provide a more intuitive and distraction-free music experience for users in home and workspace environments.

# Competencies

R, Quarto, Git, Python, Excel, SQL, AutoCAD, SAP

# Hobbies

Guitar, Volleyball
